/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SocialLink = IDL.Record({
  'id' : IDL.Text,
  'cta' : IDL.Text,
  'title' : IDL.Text,
  'href' : IDL.Text,
  'description' : IDL.Text,
});
export const SiteData = IDL.Record({
  'bio' : IDL.Text,
  'links' : IDL.Vec(SocialLink),
  'contactEmail' : IDL.Text,
});

export const idlService = IDL.Service({
  'claimOwnership' : IDL.Func([], [IDL.Bool], []),
  'getSiteData' : IDL.Func([], [SiteData], ['query']),
  'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
  'setSiteData' : IDL.Func([SiteData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SocialLink = IDL.Record({
    'id' : IDL.Text,
    'cta' : IDL.Text,
    'title' : IDL.Text,
    'href' : IDL.Text,
    'description' : IDL.Text,
  });
  const SiteData = IDL.Record({
    'bio' : IDL.Text,
    'links' : IDL.Vec(SocialLink),
    'contactEmail' : IDL.Text,
  });
  
  return IDL.Service({
    'claimOwnership' : IDL.Func([], [IDL.Bool], []),
    'getSiteData' : IDL.Func([], [SiteData], ['query']),
    'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
    'setSiteData' : IDL.Func([SiteData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };